name: Deploy to Oracle VM

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    name: Deploy to Oracle VM
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      - name: Deploy to VM via SSH
        run: |
          ssh -o StrictHostKeyChecking=no opc@170.9.50.175 << 'EOF'
            cd /home/opc/projects/patient-management
            git pull origin deploy
            docker compose down
            docker compose up -d --build
          EOF
